development:
  adapter: postgresql
  database: archmage_development
  username: postgres
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: archmage_test
  username: postgres
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: archmage_production
  pool: 5
